### ISSUE TITLE
AutoDeserializeConfirmService should have separate methods per endpoint

### ISSUE THREAD

**Issue by sfackler** [palantir/conjure-verification#175]
Body tests involve 2 services:

* `AutoDeserializeService`, which has separate endpoints for each body type.
* `AutoDeserializeConfirmService`, which has a single endpoint taking an `any` body.

This approach works fine in languages like Java that implement `any` via a "universally compatible" super type (i.e. `Object`), or languages like Python that are dynamically typed.

However, the Rust implementation of conjure doesn't do this, since that universal super type doesn't exist. Instead it uses a type roughly comparable to Jackson's `ObjectNode`. This means that the `AutoDeserializeConfirmTest` isn't really testing the serialization of Conjure types onto the wire, but rather the serialization of Conjure types to our `any` type.

`AutoDeserializeConfimService` should instead mirror `AutoDeserializeService` and have separate endpoints for each body type. This can be done without needing to modify the server, since the current endpoint has the right "shape".

**Comment by ferozco** [comment]
Sounds like a reasonabl request, happy to look into it
