### ISSUE TITLE
clearer explanation of test harness workflow

### ISSUE THREAD

**Issue by jdhenke** [palantir/conjure-verification#39]
/cc @nmiyake

I'm currently working on implementing the verification harness for conjure-go and was only able to piece together how to do this by looking at other test harness implementations ([python](https://github.com/palantir/conjure-python/blob/cc9c9775948f30fa6fee645db95e4ce75394895e/conjure-python-verifier/python/test/client/test_verify_spec.py), [java](https://github.com/palantir/conjure-java/blob/41b8848fdbf8e77e4adb8e9ed85ee3a5ccc64c8a/conjure-java-verifier/src/test/java/com/palantir/conjure/java/compliance/AutoDeserializeTest.java#L83)) and talking with folks involved in the [RFC](https://github.com/palantir/conjure/blob/develop/docs/rfc/004-consistent-wire-format-test-cases.md).

An english explanation of how these canonical implementations typically work would be really helpful. The outline (with some questions) as I understand it is:

* run the docker image
* using your generator, generate bindings for the test cases and verification server in your language
  * how/where should we get the IR for the test cases?
* write the a test suite that
  * instantiates an AutoDeserializeServiceClient, AutoDeserializeConfirmServiceClient and the Single*ServiceClient
  * reads in the test case JSON from disk
    * how/where should we get this JSON?
  * for each test case
    * using reflection, find and invoke the method on the service client
      * the arguments should be the index of the test case
      * for the Single* service clients, you will also need to reflect the types of the expected arguments on that method and instantiate a value of that type and populate it with the value from the test JSON.
    * for the AutoDeserialize, you also need to verify the response by using the AutoDeserializeConfirm service.
* then is there an verification server endpoint you must hit to verify all test cases have been hit?

**Comment by dansanduleac** [comment]
Wrote up documentation on both verification-server and verification-client in #82
